#!/bin/bash
# set up root
XPWD=`pwd`
echo $XPWD

source ./setup.sh

ln -s $DELPHES delphes 

rm -f analysis 
make -f Makefile


NEVENTS=100000

XF="rfast004"
rm -f out_ann
ln -s ../builder/out_ann_$XF out_ann
DIR=/netapp/data/hepsim/events/pp/14tev/mg5_ttbar_jet/$XF
rm -f data.in
Make_input $DIR/
head -n 20  data.in > a
mv a data.in
echo "Run $XF"
./analysis $NEVENTS
mv Analysis.root out_root/$XF.root


XF="rfast006"
rm -f out_ann
ln -s ../builder/out_ann_$XF out_ann
DIR=/netapp/data/hepsim/events/pp/14tev/mg5_ttbar_jet/$XF
rm -f data.in
Make_input $DIR/
head -n 20  data.in > a
mv a data.in
echo "Run $XF"
./analysis $NEVENTS
mv Analysis.root out_root/$XF.root







